# Generated by Django 6.0.1 on 2026-03-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('software_developer', 'Software Developer'), ('graphic_designer', 'Graphic Designer'), ('web_designer', 'Web Designer'), ('ui_ux_designer', 'UI/UX Designer'), ('business_analyst', 'Business Analyst')], max_length=50)),
                ('dob', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('primary_contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alt_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhaar_card', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('emergency_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
