# Generated by Django 6.0.1 on 2026-03-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings'), ('current', 'Current')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('software_developer', 'Software Developer'), ('graphic_designer', 'Graphic Designer'), ('web_designer', 'Web Designer'), ('ui_ux_designer', 'UI/UX Designer'), ('business_analyst', 'Business Analyst')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_no',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_person',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_relationship',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/pan/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='primary_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
