# Generated by Django 6.0.1 on 2026-03-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_account_holder_name_employee_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='device_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
