# Generated by Django 6.0.1 on 2026-04-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_workshift_employeeshift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeshift',
            name='end_date',
        ),
    ]
