# Generated by Django 6.0.1 on 2026-04-02 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employeeshift_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshift',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignment', to='employee.employee'),
        ),
    ]
