# Generated by Django 6.0.1 on 2026-04-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employeeshift_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
