# Generated by Django 6.0.1 on 2026-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_temp_password',
            field=models.BooleanField(default=False),
        ),
    ]
