# Generated by Django 6.0.1 on 2026-03-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('FESTIVAL', 'Festival')], max_length=10)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('max_allowed_leaves', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance_holiday',
                'ordering': ['date'],
            },
        ),
    ]
