# Generated by Django 6.0.1 on 2026-04-02 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancelog_permission_dailyattendance'),
        ('employee', '0007_alter_employeeshift_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_permissions', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='permission',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
