# Generated by Django 6.0.1 on 2026-04-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_permission_approved_by_permission_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='approved_by',
        ),
    ]
