# Generated by Django 6.0.1 on 2026-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_permission_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='extra_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='ot_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
