# Generated by Django 6.0.1 on 2026-04-08 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_overtimerecord'),
        ('employee', '0010_employee_email_sent_employee_is_temp_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('permission_type', models.CharField(choices=[('MID_DAY', 'Mid Day'), ('END_DAY', 'End Day')], max_length=10)),
                ('reason', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('expected_end_time', models.DateTimeField()),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('return_image', models.ImageField(blank=True, null=True, upload_to='permissions/')),
                ('return_latitude', models.FloatField(blank=True, null=True)),
                ('return_longitude', models.FloatField(blank=True, null=True)),
                ('location_valid', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=10)),
                ('usage_flag', models.CharField(blank=True, choices=[('OK', 'Ok'), ('OVERUSED', 'Overused')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
