# Generated by Django 6.0.1 on 2026-04-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_employeepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
