# Generated by Django 6.0.1 on 2026-04-10 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_leave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='admin_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='request_type',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency'), ('PREPLANNED', 'Pre-planned')], default='EMERGENCY', max_length=12),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeepermission',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeepermission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=10),
        ),
    ]
