# Generated by Django 6.0.1 on 2026-04-16 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_employeepermission_admin_remarks_and_more'),
        ('employee', '0010_employee_email_sent_employee_is_temp_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(help_text='OT start time')),
                ('end_time', models.TimeField(help_text='OT end time')),
                ('reason', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin')], default='employee', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='False means this record has been superseded. Never deleted.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text="The user (admin or employee's linked user) who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_requests_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='employee.employee')),
                ('replaced_by', models.OneToOneField(blank=True, help_text='Points to the new record that replaced this one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='attendance.overtimerequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_request_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_overtime_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
