# Generated by Django 6.0.1 on 2026-04-17 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_overtimerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimerequest',
            name='date',
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='end_date',
            field=models.DateField(blank=True, help_text='Last day of OT range (inclusive)', null=True),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Admin-side notes (visible to admin only)'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='start_date',
            field=models.DateField(blank=True, help_text='First day of OT range', null=True),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='end_time',
            field=models.TimeField(help_text='Daily OT end time'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = superseded by a newer record. Never physically deleted.'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='replaced_by',
            field=models.OneToOneField(blank=True, help_text='When this record is disabled, points to the new record that replaced it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='attendance.overtimerequest'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='start_time',
            field=models.TimeField(help_text='Daily OT start time'),
        ),
    ]
