# Generated by Django 6.0.1 on 2026-04-18 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_overtimerequest_date_overtimerequest_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimerequest',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='start_time',
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='time_slots',
            field=models.JSONField(default=list, help_text="List of time slots. Format: [{'start_time': 'HH:MM', 'end_time': 'HH:MM'}, ...]"),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated total hours', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 1), help_text='Last day of OT range (inclusive)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 1), help_text='First day of OT range'),
            preserve_default=False,
        ),
    ]
